### ISSUE TITLE
`Obsolete` Attribute

### ISSUE THREAD

**Issue by joshua-light** [candy-kingdom/summary#23]
We need to treat the `Obsolete` attribute in a specific way.

**Comment by kostiantxn** [comment]
We could cross obsolete members. For example, suppose `Summary.Doc` is marked as `Obsolete`:

# ~~Summary.Doc~~
```cs
[Obsolete]
public record Doc(DocMember[] Members)
```

A document parsed from the source code or an assembly.

## Fields
### Empty
```cs
public static readonly Doc Empty
```

...

The `Empty` field is not crossed as it is not marked as `Obsolete`.

**Comment by joshua-light** [comment]
Looks awesome!

What do you think about including the string value of the attribute like this:

---

# ~~Summary.Doc~~
_You shouldn't use this type anymore. Use `AwesomeDoc` instead._
```cs
[Obsolete("You shouldn't use this type anymore. Use `AwesomeDoc` instead."]
public record Doc(DocMember[] Members)
```

A document parsed from the source code or an assembly.

## Fields
### Empty
```cs
public static readonly Doc Empty
```

...

---

Few minor questions, though:
- Should we include the `Obsolete` attribute in the type declaration code-snippet if we're rendering the comment separately?
- Should we also consider a future improvement that will maybe somehow parse mentioned types or methods in the comment (like `AwesomeDoc`) and automatically insert the link to the type if it's possible?

**Comment by kostiantxn** [comment]
> What do you think about including the string value of the attribute...

Absolutely! With GitHub-flavoured Markdown, we can even render it as follows:

# ~~Summary.Doc~~

> [!WARNING]
> You shouldn't use this type anymore. Use `AwesomeDoc` instead.

> Should we include the Obsolete attribute in the type declaration code-snippet if we're rendering the comment separately?

I think we shouldn't in order to avoid duplication.

> Should we also consider a future improvement that will maybe somehow parse mentioned types or methods in the comment (like `AwesomeDoc`) and automatically insert the link to the type if it's possible?

I think it would be very helpful! But maybe we should create a separate ticket for this?
