### ISSUE TITLE
Scan one file and generate one markdown.

### ISSUE THREAD

**Issue by tsanyqudsi** [candy-kingdom/summary#40]
Due the nature of #24 and my own [summary-ide-extension](https://github.com/tsanyqudsi/summary-ide-extensions), do you think it would be possible to just scan and generate just one file ?

**Comment by tsanyqudsi** [comment]
Based on @joshua-light comment "[just add new files/edit existing ones and commit both source files and documentation automatically into the same repository.](https://github.com/candy-kingdom/summary/issues/29#issuecomment-1837133192_)" It would be nice if we can add the output folder too with absolute path just for the ide plugins.

Example :
Instead of `./docs` we can use `~/projects/documentation/docs` in Linux / Mac or `$USER_PROFILE/Documents/projects/documentation/docs` in Windows.

The default should be `<project_root>/docs`

**Comment by joshua-light** [comment]
Hey, sorry for the delayed answer, have a lot of work.

I've added a simple fix in (7d10cb0) so it should be relatively easy to parse and generate a single file like this:
```cs
const string input = "./src/SomeFile.cs";
const string output = "./docs";

await new SummaryPipeline()
    .UseRoslynParser(input)
    .UseMdRenderer(output)
    .Run();
```

**Comment by joshua-light** [comment]
Regarding absolute path, I've tried doing something like this and it worked okay:
```cs
const string input = "./src/SomeFile.cs";
const string output = "C://Some Directory/docs";

await new SummaryPipeline()
    .UseRoslynParser(input)
    .UseMdRenderer(output)
    .Run();
```

So, it's possible to specify absolute path instead of the relative one for output folder of Markdown files. Is this something you're looking for?

**Comment by tsanyqudsi** [comment]
> Hey, sorry for the delayed answer, have a lot of work.

It's ok, it's 02.41 AM and I'm still awake managing my team's gh issues, so yea... I totally understand.

> I've added a simple fix in (https://github.com/candy-kingdom/summary/commit/7d10cb0757f938de20efbb70060d58cbda7903a0) 

I will wait for another version to release, glad to know it's already commited.

> Is this something you're looking for?

Yes, thank you. Will close this issue.
